app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongo:
      host: localhost
      port: 27017